# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'marko-cerovac/material.nvim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/lualine.lua
'''

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/vim-gitgutter.lua
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/coc.lua
'''

[[plugins]]
repo = 'wakatime/vim-wakatime'
on_i = 1

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1
