# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'marko-cerovac/material.nvim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/lualine.lua
'''

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/vim-gitgutter.lua
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

# for vim-lsp

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/lsp/general.lua
'''

[[plugins]]
repo =  'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo =  'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/completion/nvim-cmp.lua
'''

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'onsails/lspkind.nvim'
hook_post_source = '''
source ~/dotfiles/vimrc/lua/plugins/completion/lspkind.lua
'''

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/lsp/mason.lua
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.x'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/telescope/telescope.lua
'''

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_add = '''
lua << EOF
require("nvim-autopairs").setup {}
EOF
'''

[[plugins]]
repo = 'sidebar-nvim/sidebar.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/sidebar.lua
'''

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'nvim-neo-tree/neo-tree.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/neo-tree.lua
'''

[[plugins]]
repo = 'folke/todo-comments.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/todo-comments.lua
'''
