# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# 目に優しいカラースキーム
[[plugins]]
repo = 'morhetz/gruvbox'

# molokai
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/dotfiles/vimrc/plugins/defx.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'


[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
source ~/dotfiles/vimrc/plugins/vim-gitgutter.vim
'''

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'anned20/vimsence'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
source ~/dotfiles/vimrc/plugins/airline-theme.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_completion_enabled = 0
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
source ~/dotfiles/vimrc/plugins/unite.vim
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
source ~/dotfiles/vimrc/plugins/coc.vim
'''

[[plugins]]
repo = 'neoclide/coc-rls'
on_ft = ['rust']

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/dotfiles/vimrc/plugins/denite.vim
'''
