# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

# 目に優しいカラースキーム
[[plugins]]
repo = 'marko-cerovac/material.nvim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
source ~/dotfiles/vimrc/plugins/vim-gitgutter.vim
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = "TSUpdate"
