# tomlのsyantax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# TypeScript専用
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'othree/xml.vim'
on_ft = ['xml']

# clang用
[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c']

# 閉じタグ
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['typescript']
hook_add = '''
source ~/dotfiles/vimrc/plugins/vim-closetag.vim
'''

# rust用
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
let g:rust_doc#define_map_K = 0
'''

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = 'dart'

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'pantharshit00/vim-prisma'
on_ft = ['prisma']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile']

[[plugins]]
repo = 'sudar/vim-arduino-syntax'
on_ft = ['arduino']

[[plugins]]
repo = 'stevearc/vim-arduino'
on_ft = ['arduino']
