# snippets関連
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
source ~/dotfiles/vimrc/plugins/ultisnip.vim
'''

# python専用
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

# tomlのsyantax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'javascript.ejs']

# TypeScript専用
[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'othree/xml.vim'
on_ft = ['xml']

# HTML/CSS用
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html']
hook_add = '''
source ~/dotfiles/vimrc/plugins/emmet.vim
'''

# clang用
[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c']

# 閉じタグ
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['typescript']
hook_add = '''
source ~/dotfiles/vimrc/plugins/vim-closetag.vim
'''

# rust用
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
let g:rustfmt_autosave = 1
let g:rust_doc#define_map_K = 0
'''

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = 'dart'

[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['graphql']

[[plugins]]
repo = 'pantharshit00/vim-prisma'
on_ft = ['prisma']
