[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['dart']

[[plugins]]
repo = 'Shougo/neco-vim'
on_source = ['deoplete.nvim']

# snippets関連
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
let g:UltiSnipsExpandTrigger="<C-f>"
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetsDir = '~/dotfiles/vimrc/snippets'
set runtimepath+=~/dotfiles/vimrc/snippets
'''

# dart専用
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']

# python専用
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

# tomlのsyantax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'javascript.ejs']

# TypeScript専用
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript']

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
on_ft = ['markdown']


# JavaScript専用
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript'] 

# kotlin専用
[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'othree/xml.vim'
on_ft = ['xml']

# Rubyの自動補完
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
on_ft = ['ruby']
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
    \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
      \}
'''

# HTML/CSS用
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html']
hook_add = '''
let g:user_emmet_mode = 'iv'
let g:user_emmet_leader_key = '<C-Y>'
let g:use_emmet_complete_tag = 1

'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
let g:go_fmt_command = "goimports"
'''

# clang用
[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c']

# 閉じタグ
[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['typescript']
hook_add = '''
let g:closetag_filenames = "*.tsx"
let g:closetag_xhtml_filenames = "*.tsx"
let g:closetag_filetypes = "*.tsx"
let g:closetag_xhtml_filetypes = "*.tsx"
'''
