# snippets関連
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
source ~/dotfiles/vimrc/plugins/ultisnip.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/dotfiles/vimrc/plugins/defx.vim
'''
on_cmd = 'Defx'

[[plugins]]
repo = 'kristijanhusak/defx-git'
on_cmd = 'Defx'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/dotfiles/vimrc/plugins/denite.vim
'''
on_cmd = "Denite"

[[plugins]]
repo = 'wakatime/vim-wakatime'
on_i = 1

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'honza/vim-snippets'
on_i = 1

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = "TSUpdate"
on_event = "VimEnter"
hook_post_source = '''
source ~/dotfiles/vimrc/lua/plugins/treesitter.lua
'''
