[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/defx.lua
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'wakatime/vim-wakatime'
on_i = 1

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = "TSUpdate"
on_event = 'VimEnter'
hook_post_source = '''
source ~/dotfiles/vimrc/lua/plugins/treesitter.lua
'''
