[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/dotfiles/vimrc/lua/plugins/defx.lua
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'wakatime/vim-wakatime'
on_i = 1

[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1
