# snippets関連
[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
source ~/dotfiles/vimrc/plugins/ultisnip.vim
'''

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_completion_enabled = 0
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'
